server:
  port: 8080

aws:
  region:
    static: ${AWS-REGION:us-east-2}
  output: json
  credentials:
    access-key: ${YOUR_ACCESS_KEY:test}
    secret-key: ${YOUR_SECRET_KEY:test}
  bucket:
    name: ${BUCKET_NAME:amazon-bucket-test}
  stack:
    auto: false